# Automatically generated by Pynguin.
import ansible.plugins.action.wait_for_connection as module_0

def test_case_0():
    str_0 = 'XC'
    list_0 = [str_0, str_0, str_0, str_0]
    timed_out_exception_0 = module_0.TimedOutException(*list_0)

def test_case_1():
    str_0 = 'XC'
    list_0 = [str_0, str_0, str_0, str_0]
    timed_out_exception_0 = module_0.TimedOutException(*list_0)
    list_1 = [timed_out_exception_0, list_0]
    timed_out_exception_1 = module_0.TimedOutException(*list_1)

def test_case_2():
    str_0 = '6"a\x0c\trk^tXsH'
    bool_0 = False
    bool_1 = None
    str_1 = 'rHhLi8XP:<'
    bytes_0 = b'm4J\x00\x0eF\xda\x16'
    timed_out_exception_0 = module_0.TimedOutException()
    list_0 = [timed_out_exception_0, timed_out_exception_0, timed_out_exception_0]
    int_0 = 196
    str_2 = '\\O}p<n0C'
    dict_0 = {str_2: int_0, str_0: str_2, str_0: bool_1, str_2: int_0}
    bytes_1 = b'\xb7\x91\xf6\x89E'
    action_module_0 = module_0.ActionModule(list_0, bool_0, dict_0, bytes_1, bytes_0, bytes_0)
    float_0 = 512.0
    dict_1 = {}
    list_1 = [str_1, bytes_0]
    var_0 = action_module_0.do_until_success_or_timeout(list_0, float_0, dict_1, list_1)
    timed_out_exception_1 = module_0.TimedOutException(*list_1)
    tuple_0 = (dict_0,)
    action_module_1 = module_0.ActionModule(list_0, list_0, int_0, action_module_0, tuple_0, bytes_1)