# Automatically generated by Pynguin.
import ansible.plugins.action.unarchive as module_0

def test_case_0():
    try:
        bool_0 = True
        bytes_0 = b'\x01\xb1'
        action_module_0 = None
        dict_0 = {bytes_0: bytes_0, bytes_0: action_module_0, bytes_0: action_module_0}
        float_0 = -191.0
        set_0 = set()
        action_module_1 = module_0.ActionModule(dict_0, dict_0, float_0, dict_0, set_0, bytes_0)
        var_0 = action_module_1.run(bool_0)
    except BaseException:
        pass

def test_case_1():
    try:
        float_0 = None
        set_0 = {float_0, float_0}
        bool_0 = False
        float_1 = None
        str_0 = 'hostnqn'
        list_0 = []
        int_0 = 79
        bool_1 = False
        float_2 = 1198.0
        action_module_0 = module_0.ActionModule(bool_0, list_0, int_0, bool_1, float_2, list_0)
        float_3 = 1994.758161
        action_module_1 = module_0.ActionModule(float_1, str_0, action_module_0, int_0, float_3, list_0)
        int_1 = 3
        tuple_0 = None
        action_module_2 = module_0.ActionModule(action_module_1, int_1, bool_1, bool_0, action_module_1, tuple_0)
        list_1 = []
        str_1 = 'here goes the callback...'
        list_2 = [bool_0]
        dict_0 = {str_1: bool_0, str_1: list_1}
        action_module_3 = module_0.ActionModule(bool_0, list_1, str_1, list_2, list_2, dict_0)
        var_0 = action_module_3.run(float_0, set_0)
    except BaseException:
        pass