# Automatically generated by Pynguin.
import ansible.plugins.callback.junit as module_0

def test_case_0():
    pass

def test_case_1():
    callback_module_0 = module_0.CallbackModule()

def test_case_2():
    callback_module_0 = module_0.CallbackModule()
    var_0 = callback_module_0.v2_playbook_on_stats(callback_module_0)

def test_case_3():
    str_0 = 'some_uuid'
    str_1 = 'some_name'
    str_2 = 'some/path'
    str_3 = 'some_play'
    str_4 = 'setup'
    task_data_0 = module_0.TaskData(str_0, str_1, str_2, str_3, str_4)
    str_5 = 'some_host_uuid'
    str_6 = 'some_host_name'
    str_7 = 'ok'
    str_8 = 'some_result'
    host_data_0 = module_0.HostData(str_5, str_6, str_7, str_8)
    var_0 = task_data_0.add_host(host_data_0)
    var_1 = host_data_0.uuid
    str_9 = 'included'
    host_data_1 = module_0.HostData(str_5, str_6, str_9, str_8)
    var_2 = task_data_0.add_host(host_data_1)
    var_3 = host_data_1.uuid
    var_4 = task_data_0.add_host(host_data_1)
    str_10 = 'Host has been added twice, second run should have raised an exception'
    var_5 = AssertionError(str_10)