# Automatically generated by Pynguin.
import isort.exceptions as module_0

def test_case_0():
    try:
        str_0 = '|'
        str_1 = 'asdict() should be called on dataclass instances'
        str_2 = '/src'
        dict_0 = {str_1: str_2, str_2: str_0}
        dict_1 = {str_0: dict_0, str_2: dict_0, str_2: dict_0, str_0: dict_0}
        unsupported_settings_0 = module_0.UnsupportedSettings(dict_1)
    except BaseException:
        pass