# Automatically generated by Pynguin.
import urllib.error as module_0
import ansible.galaxy.api as module_1

def test_case_0():
    try:
        dict_0 = {}
        bytes_0 = None
        list_0 = [bytes_0]
        str_0 = 'C/a\x0c+\t&su#i\t'
        collection_version_metadata_0 = None
        h_t_t_p_error_0 = module_0.HTTPError(bytes_0, list_0, str_0, collection_version_metadata_0, list_0)
        int_0 = -2394
        galaxy_a_p_i_0 = module_1.GalaxyAPI(int_0, bytes_0, dict_0)
        var_0 = galaxy_a_p_i_0.__repr__()
        galaxy_error_0 = module_1.GalaxyError(h_t_t_p_error_0, int_0)
    except BaseException:
        pass

def test_case_1():
    try:
        str_0 = 'ssh_retry: attempt: %d, caught exception(%s) from cmd (%s), pausing for %d seconds'
        float_0 = -1064.7102
        str_1 = '&p*e9W=i'
        dict_0 = {float_0: str_0, str_0: str_1, float_0: str_0, str_1: str_1}
        collection_version_metadata_0 = None
        collection_metadata_0 = None
        collection_version_metadata_1 = module_1.CollectionVersionMetadata(str_0, float_0, dict_0, collection_version_metadata_0, collection_metadata_0, dict_0)
        set_0 = {collection_version_metadata_1, collection_version_metadata_1, str_0, str_0}
        int_0 = 1960
        galaxy_a_p_i_0 = module_1.GalaxyAPI(int_0, collection_metadata_0, dict_0, dict_0, set_0)
        var_0 = galaxy_a_p_i_0.__lt__(galaxy_a_p_i_0)
    except BaseException:
        pass